development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: team@bankmybiz.com
  :password: "B@nkMyB!z987"
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: team@bankmybiz.com
  :password: "B@nkMyB!z987"
  :enable_starttls_auto: true