development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bankmybiz@gmail.com
  :password: "Change!23"
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bankmybiz@gmail.com
  :password: "Change!23"
  :enable_starttls_auto: true